- hosts: localhost
  tasks:
  - name: Install brew packages
    homebrew:
      name: 
      - bat
      - jq
      - stow
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
      - exa
      - tmux
  - name: Install brew casks
    homebrew_cask:
      name:
      - karabiner-elements
      - iterm2
