- hosts: localhost
  tasks:


  - name: Update brew
    homebrew:
      update_homebrew: yes

  - name: Install brew packages
    homebrew:
      name: 
      - bat
      - jq
      - stow
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
      - exa
      - tmux
      - tldr
      state: present

  - name: Install brew casks
    homebrew_cask:
      name:
      - karabiner-elements
      # - iterm2
      - alacritty
      state: present
      greedy: yes

